### PR TITLE
Upgrade to React 16

### PR DESCRIPTION
**Pull request by filipposarzana**
Upgrade packages:
- "eslint": "^4.7.2"
- "eslint-plugin-react": "^7.4.0",
- "react": "^16.0.0",
- "react-dom": "^16.0.0",

Introduced `package-lock.json`, upgrade eslint standard and references on `index.html`

### CODE REVIEW

**Comment by fes300** [comment]
any news on this?

**Comment by dreyescat** [comment]
It should solve issue #58 too.

**Comment by dreyescat** [comment]
Released in version [0.9.0](https://github.com/dreyescat/react-rating/releases/tag/v0.9.0).

**Comment by filipposarzana** [comment]
Awesome, tested right now and it works! and solve also #58 as you said

Do you mind if in the next weeks i'll work on some improvements on this library? we are using it massively in our codebase :smile:

**Comment by dreyescat** [comment]
Of course! You are very welcome to contribute! We @mkarajohn and I were in the middle of it in [v1](https://github.com/dreyescat/react-rating/tree/v1) branch. He already introduced some improvements. Would you mind to check this branch? Maybe it would be a better starting point.

Check issue #50 for more info.

**Comment by filipposarzana** [comment]
Cool! Sure :smile: i'll start from there ;)

**Pull request merged**
