### PR TITLE
Fix bug where re-rendering react-rating would cause it to reset its value to initalRating

### PR DESCRIPTION
**Pull request by tuckerconnelly**

### CODE REVIEW

**Comment by mkarajohn** [comment]
Thanks for taking the time to open up this PR. Could you possibly also open an issue, describing the problem you encountered?

**Comment by tuckerconnelly** [comment]
<Rating> was getting re-rendered for some reason--I think it was receiving new props. This caused it to receive props again and re-set `state.value` to initalRating. So you'd click it and it'd call `onChange` twice, once with the new value and again with the initialRating

**Comment by dreyescat** [comment]
@tuckerconnelly Could you check if the new release [1.1.2](https://github.com/dreyescat/react-rating/releases/tag/v1.1.2) solves your re-render issue? I think it was related to #89 and maybe it solves your issue too.

**Comment by DanielOberg** [comment]
I got this error in release 1.1.2, where it would reset to initial rate if parent was changed. Modified componentWillReceiveProps(nextProps) to
```
  static getDerivedStateFromProps(nextProps, prevState) {
    return {
      value: nextProps.initialRating
    };
  }
```
to fix it.

https://reactjs.org/docs/react-component.html#static-getderivedstatefromprops

**Pull request closed without merging**
