### PR TITLE
Add touch events for mobile devices

### PR DESCRIPTION
**Pull request by djkwagala**
@dreyescat  I added some modifications to handle touch events (TouchMove, and TouchEnd) using pre-existing functionality.

### CODE REVIEW

**Comment by djkwagala** [comment]
@dreyescat please have a review and rebase to master if it okay.

**Comment by dreyescat** [comment]
That's nice! It allows to rate sliding your finger :clap:

**Comment by dreyescat** [comment]
Merged and published in [v0.8.0](https://github.com/dreyescat/react-rating/releases/tag/v0.8.0).

**Comment by trektravel** [comment]
I just tried this in v0.9.0 and touch on mobile doesn't seem to work yet. I am wondering what I am missing.

**Comment by Jaikant** [comment]
I just tried this in v0.9.0 and touch on mobile doesn't seem to work yet. I am wondering what I am missing.

**Pull request merged**
