### PR TITLE
Changed inline-blocks to flex for better centering

### PR DESCRIPTION
**Pull request by XenorPLxx**
I've had to move my PR from #122 to separate branch, as I'm using my forked master with `lib` folder in one of my projects.

This PR contains only changes to `*.jsx` files.

I've provided explanation to `lineHeight: 0` in #122.

### CODE REVIEW

**Comment by dreyescat** [comment]
Thanks for fixing the PR. These are the files I am interested in.

I'm still unsure about this solution... Changing the main container (`Rating.jsx`) from `inline-block` to `flex` seems logical. It fits with the idea of having a *row* of symbols. The dark part I am trying to make sense is regarding `RatingSymbol.jsx`. Why using `flex` on a symbol? It is not supposed to be a container but an item. But I have checked myself that using `flex` here gets rid of this annoying extra height 😅. I think it is related to how `font-size` affects `inline-block` elements but it does not to `flex` elements. I don't have a clear answer yet.

About `line-height: 0`... This solution breaks the *React span element rating* [demo](http://dreyescat.github.io/react-rating/).
Check this [text symbol](https://codepen.io/dreyescat/pen/OGaeKN?editors=1111) code example. I pointed to your `build` branch that includes these changes. As you can see it forces me to overwrite the *normal* text behavior.

**Comment by dreyescat** [comment]
Could you provide a small demo that I could play with reproducing the issue? You can base the demo on the previous Codepen.

**Comment by dreyescat** [comment]
I have a hunch that setting `font-size: 0` could solve the problem 🤔.

**Comment by XenorPLxx** [comment]
Sorry, I couldn't figure out how to include those star icons in codepen.
Here's codesandbox with example https://codesandbox.io/s/94z5yxovkp?fontsize=14
It uses `react-rating` from npm.

And here's how it look with my changes:
image

**Comment by dreyescat** [comment]
Codesandbox is perfect too.

In your `RatingDisplay` component just add `fontSize: 0` to the style:

```jsx
    <Rating
      style={{fontSize: 0}}
      initialRating={Number.parseFloat(`${rating}`)}
      readonly
      max={5}
      emptySymbol={<Star color="#cc9405" size={16} />}
      fullSymbol={<Star color="#cc9405" fill="#ffbd00" size={16} />}
    />
```

The `style` property is propagated to the container element. Does it do the trick?

**Comment by XenorPLxx** [comment]
Yes, it works like a charm. Thanks for your help!

I suppose my changes are no longer needed and we can close this PR :).

**Comment by dreyescat** [comment]
I'm glad it worked!

Yep. I will close this PR then :wink:.

**Pull request closed without merging**
